// import type { ReactNode } from "react";
// import Header from "../layouts/Header";
// import Footer from "../layouts/Footer";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <head>
        {/* SAFE font loading for iOS */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Caveat:wght@500&display=swap"
          rel="stylesheet"
        />
      </head>

      <body
        suppressHydrationWarning
        style={{
          margin: 0,
          WebkitOverflowScrolling: "touch",
        }}
      >
        {/* <Header /> */}
        <main>{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
